import React from 'react';
import { Card, CardHeader, CardTitle, CardContent, Badge, Button } from '../components/ui';
import { Sparkles, Lightbulb, Bot, TrendingUp, Terminal, FileText, Zap } from 'lucide-react';
import { UserRole } from '../types';

interface AIToolsProps {
  role: UserRole;
}

const AITools: React.FC<AIToolsProps> = ({ role }) => {
  // Client View: Simplified Insights (Dashboard style)
  if (role === UserRole.CLIENT) {
     return (
       <div className="space-y-6">
          <div className="flex items-center justify-between">
            <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
              <Sparkles className="h-6 w-6 text-indigo-600" />
              Smart Insights
            </h1>
          </div>
          <div className="grid gap-6 md:grid-cols-2">
             <Card>
               <CardHeader><CardTitle>System Health Summary</CardTitle></CardHeader>
               <CardContent>
                  <div className="flex items-start space-x-4">
                     <div className="bg-emerald-100 p-2 rounded-lg"><Lightbulb className="h-6 w-6 text-emerald-600" /></div>
                     <div>
                        <p className="text-sm text-slate-600 leading-relaxed">
                           Systems are healthy. AI analysis detects a <strong>98% probability</strong> of stable performance for the next 24 hours based on current traffic patterns.
                        </p>
                        <p className="mt-4 text-xs text-slate-400">Generated by Gemini Pro • 2 mins ago</p>
                     </div>
                  </div>
               </CardContent>
             </Card>
             <Card>
               <CardHeader><CardTitle>Usage Anomaly Detection</CardTitle></CardHeader>
               <CardContent>
                  <div className="space-y-4">
                     <div className="flex items-center justify-between text-sm">
                        <span className="text-slate-600">API Requests</span>
                        <span className="text-emerald-600 font-medium">Normal Range</span>
                     </div>
                     <div className="w-full bg-slate-100 rounded-full h-2">
                        <div className="bg-slate-400 h-2 rounded-full w-[60%]"></div>
                     </div>
                     <div className="flex items-center justify-between text-sm">
                        <span className="text-slate-600">Storage I/O</span>
                        <span className="text-emerald-600 font-medium">Normal Range</span>
                     </div>
                     <div className="w-full bg-slate-100 rounded-full h-2">
                        <div className="bg-slate-400 h-2 rounded-full w-[30%]"></div>
                     </div>
                  </div>
               </CardContent>
             </Card>
          </div>
       </div>
     );
  }

  // Internal View (Lead & Agent): Operational Tools + Chatbot
  return (
    <div className="space-y-6 pb-10">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 flex items-center gap-2">
             <Sparkles className="h-6 w-6 text-indigo-600" />
             AI Operations Center
          </h1>
          <p className="text-sm text-slate-500">
             {role === UserRole.LEAD 
               ? 'Strategic analysis and predictive risk assessment.' 
               : 'Operational diagnostics and automated log analysis.'}
          </p>
        </div>
      </div>

      {/* SECTION 1: Mock Operational Tools */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
         {/* Feature Card */}
         <Card className="h-full flex flex-col">
            <CardHeader>
               <CardTitle>{role === UserRole.LEAD ? 'Predictive Risk Models' : 'Log Pattern Analyzer'}</CardTitle>
            </CardHeader>
            <CardContent className="flex-1">
               {role === UserRole.LEAD ? (
                  <div className="space-y-4">
                     <div className="p-4 bg-indigo-50 rounded-lg border border-indigo-100">
                        <div className="flex items-center gap-2 mb-2">
                           <TrendingUp className="h-4 w-4 text-indigo-600" />
                           <span className="font-semibold text-indigo-900">Pattern Detected</span>
                        </div>
                        <p className="text-sm text-indigo-800">
                           Incident volume spikes projected for next Tuesday at 14:00 UTC based on historical deployment data.
                        </p>
                     </div>
                     <div className="h-32 bg-slate-50 rounded border border-dashed border-slate-300 flex flex-col items-center justify-center text-slate-400 gap-2">
                        <TrendingUp className="h-6 w-6 opacity-50" />
                        <span className="text-xs">Risk Heatmap Visualization</span>
                     </div>
                  </div>
               ) : (
                  <div className="space-y-4">
                     <div className="relative">
                        <div className="absolute top-2 left-2 px-2 py-0.5 bg-slate-800 text-slate-400 text-[10px] rounded">raw_logs.txt</div>
                        <textarea
                           className="w-full h-40 p-4 pt-8 text-xs font-mono bg-slate-900 text-slate-50 rounded-md resize-none focus:ring-2 focus:ring-indigo-500 outline-none"
                           placeholder="Paste server logs here..."
                           defaultValue={`[Error] Connection refused at 10.0.1.5:5432
[Warning] Connection retry 1/3 failed
[Critical] Connection pool exhausted
[Info] Failover process initiated`}
                        />
                     </div>
                     <Button className="w-full bg-slate-900 hover:bg-slate-800">
                        <Terminal className="h-4 w-4 mr-2" />
                        Analyze Root Cause
                     </Button>
                  </div>
               )}
            </CardContent>
         </Card>

         {/* Actions Card */}
         <Card className="h-full flex flex-col">
            <CardHeader>
               <CardTitle>Recommended Actions</CardTitle>
            </CardHeader>
            <CardContent className="flex-1">
                <div className="space-y-3">
                   <div className="flex items-center justify-between p-3 border border-slate-100 rounded-lg hover:bg-slate-50 transition-colors group">
                      <div className="flex items-center gap-3">
                         <div className="p-2 bg-emerald-100 text-emerald-600 rounded group-hover:bg-emerald-200"><Zap className="h-4 w-4" /></div>
                         <div className="text-sm">
                            <p className="font-medium text-slate-900">Auto-Remediation</p>
                            <p className="text-xs text-slate-500">Restart stalled worker nodes</p>
                         </div>
                      </div>
                      <Button variant="outline" size="sm">Run</Button>
                   </div>
                   
                   <div className="flex items-center justify-between p-3 border border-slate-100 rounded-lg hover:bg-slate-50 transition-colors group">
                      <div className="flex items-center gap-3">
                         <div className="p-2 bg-indigo-100 text-indigo-600 rounded group-hover:bg-indigo-200"><FileText className="h-4 w-4" /></div>
                         <div className="text-sm">
                            <p className="font-medium text-slate-900">Draft Post-Mortem</p>
                            <p className="text-xs text-slate-500">Generate report from active incident</p>
                         </div>
                      </div>
                      <Button variant="outline" size="sm">Draft</Button>
                   </div>
                   
                   <div className="p-3 bg-slate-50 rounded-lg text-xs text-slate-500 text-center italic">
                      AI suggestions based on last 4 hours of activity.
                   </div>
                </div>
            </CardContent>
         </Card>
      </div>

      {/* SECTION 2: Embedded Chatbot */}
      <Card className="overflow-hidden border border-slate-200 shadow-md">
         <CardHeader className="bg-slate-50 border-b border-slate-200 py-3">
            <div className="flex items-center justify-between">
               <div className="flex items-center gap-2">
                  <Bot className="h-5 w-5 text-indigo-600" />
                  <h3 className="font-semibold text-slate-900">External Assistant (GPTMaker)</h3>
               </div>
               <Badge variant="success" className="bg-emerald-100 text-emerald-700 border-emerald-200 px-2">
                  <span className="w-2 h-2 rounded-full bg-emerald-500 mr-1.5 animate-pulse"></span>
                  Live
               </Badge>
            </div>
         </CardHeader>
         <div className="bg-white w-full">
            <iframe 
               src="https://app.gptmaker.ai/widget/3E76F75BD0A222B0634A96DA1F24A670/iframe" 
               width="100%" 
               style={{ height: '100%', minHeight: '700px' }}
               allow="microphone;" 
               frameBorder="0"
               title="GPTMaker Chatbot"
            />
         </div>
      </Card>
    </div>
  );
};

export default AITools;